config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes for the homepage

  get '/' => 'welcome#index', as: 'home'

  # Routes for registering a new user

  resources :users, only: [:new, :create]

  # Routes for logging in for existing users

  get '/login' => 'user_sessions#new', as: 'login'

  post '/login' => 'user_sessions#create'

  delete '/logout' => 'user_sessions#destroy', as: 'logout'

  # Routes for selecting tests by Users

  resources :tests, only: [:index, :show]

  # Routes to create sessions with content 

  resources :test_sessions, only: [:create, :show, :update]

  get '/test_sessions/:id/test_complete' => 'test_sessions#test_complete', as: 'test_complete'

  # Routes to create and view reports after tests

  resources :reports, only: [:create, :show, :index, :update]

  # Routes for the admin sessions

  get '/admin/login' => 'admin_sessions#new', as: 'admin_login'

  post '/admin' => 'admin_sessions#create', as: 'admin'

  delete '/admin/logout' => 'admin_sessions#destroy', as: 'admin_logout'

  # Routes for the admin dashboard

  get '/admin/dashboard' => 'admins#dashboard', as: 'admin_dashboard'

  post '/admin/create-user' => 'admins#create_user', as: 'create_user'

  post '/admin/create-test' => 'admins#create_test', as: 'create_test'

end

app/views/admins/dashboard.html.erb
<section class="admin-dashboard">
    <div class="wrapper">
        <h1 class="tests-para">Welcome to the admin dashboard!</h1>
        <% if TestSession.all.length > 0 %>
            <h1 class="dashboard-stat">The highest scoring test score belongs to: <%= TestSession.highest_scoring_student %></h1>
            <h1 class="dashboard-stat">The most active user is: <%= User.most_active_student %></h1>
            <h1 class="dashboard-stat">The user with the fastest test session time is: <%= TestSession.student_with_fastest_test_completion %> </h1>
        <% end %>
        <h1 class="tests-para">Create a new user account: </h1>
        <% if flash[:user_notice] %>
            <%= flash[:user_notice] %>
        <% end %>

        <% if @user.errors.full_messages.length > 0 %>

            <ul>

            <% @user.errors.full_messages.each do |message| %>
            
                <li>
                
                    <%= message %>
                
                </li>

            <% end %>
            
            </ul>

        <% end %>
        <%= form_for @user, :url => create_user_path, :html => {:class => 'admin_dashboard_user'} do |f| %>
            
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name %>

            <%= f.label :age %>
            <%= f.number_field :age %>

            <%= f.label :username %>
            <%= f.text_field :username %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.submit 'Create User Account' %>

        <% end %>

        <% if flash[:test_notice] %>
            <%= flash[:test_notice] %>
        <% end %>

        <h1 class="tests-para">Create a new test</h1>
        <%= form_for @test, :url => create_test_path, :html => {:class => 'admin_dashboard_test'} do |f| %>

            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :content %>
            <%= f.text_field :content %>

            <%= f.label :language %>
            <%= f.text_field :language %>

            <%= f.label :difficulty %>
            <%= f.text_field :difficulty %>

            <%= f.submit 'Create Test'%>

        <% end %>
    </div>
</section>