config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes for the homepage

  get '/' => 'welcome#index', as: 'home'

  # Routes for registering a new user

  resources :users, only: [:new, :create]

  # Routes for logging in for existing users

  get '/login' => 'user_sessions#new', as: 'login'

  post '/login' => 'user_sessions#create'

  delete '/logout' => 'user_sessions#destroy', as: 'logout'

  # Routes for selecting tests by Users

  resources :tests, only: [:index, :show]

  # Routes to create sessions with content 

  resources :test_sessions, only: [:create, :show, :update]

  get '/test_sessions/:id/test_complete' => 'test_sessions#test_complete', as: 'test_complete'

  # Routes to create and view reports after tests

  resources :reports, only: [:create, :show, :index, :update]

  # Routes for the admin sessions

  get '/admin/login' => 'admin_sessions#new', as: 'admin_login'

  post '/admin' => 'admin_sessions#create', as: 'admin'

  delete '/admin/logout' => 'admin_sessions#destroy', as: 'admin_logout'

  # Routes for the admin dashboard

  get '/admin/dashboard' => 'admins#dashboard', as: 'admin_dashboard'

  post '/admin/create-user' => 'admins#create_user', as: 'create_user'

  post '/admin/create-test' => 'admins#create_test', as: 'create_test'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/views/welcome/index.html.erb
<%# Conditional rendering for welcoming new users %>
<section class="main">
    <div class="wrapper">
        <div class="main-content">
            <div class="main-left">
                <% if logged_in? %>

                    <h1 class="main-heading">Improve speed,<br> accuracy and overall <br> skills on the keys!</h1>
                    <p class="main-para">Take a quick test to find out how accurately <br> and quickly you type (and how to improve!)</p>

                    <%= link_to 'Start New Test', tests_path, method: :get %>
                    <%= link_to 'Completed Tests', reports_path %>

                <% elsif admin_logged_in? %>

                    <h1 class="main-heading">Manage accounts,<br> get stats <br> and figures.</h1>
                    <p class="main-para">Here you can manage the inner workings <br> of the app and get statistical insights br regarding the models.</p>
                    <%= link_to 'Go to Dashboard', admin_dashboard_path %>


                <% else %>
                    <h1 class="main-heading">Improve speed,<br> accuracy and overall <br> skills on the keys!</h1>
                    <p class="main-para para-animate">Take a quick test to find out how accurately <br> and quickly you type (and how to improve!)</p>

                    <%= link_to 'Register', new_user_path %>
                    <%= link_to 'Login', login_path %>
                    <p class="admin-login-btn">or <%= link_to 'login as Admin...', admin_login_path %></p>

                <% end %>
            </div>
            <div class="main-right">
               <img class="main-image home-image" src="https://i.ibb.co/QNbVbqB/main-illustration.png" alt="main-illustration" border="0">
            </div>
        </div>
    </div>
</section>