config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes for the homepage

  get '/' => 'welcome#index', as: 'home'

  # Routes for registering a new user

  resources :users, only: [:new, :create]

  # Routes for logging in for existing users

  get '/login' => 'user_sessions#new', as: 'login'

  post '/login' => 'user_sessions#create'

  delete '/logout' => 'user_sessions#destroy', as: 'logout'

  # Routes for selecting tests by Users

  resources :tests, only: [:index, :show]

  # Routes to create sessions with content 

  resources :test_sessions, only: [:create, :show, :update]

  get '/test_sessions/:id/test_complete' => 'test_sessions#test_complete', as: 'test_complete'

  # Routes to create and view reports after tests

  resources :reports, only: [:create, :show, :index, :update]

  # Routes for the admin sessions

  get '/admin/login' => 'admin_sessions#new', as: 'admin_login'

  post '/admin' => 'admin_sessions#create', as: 'admin'

  delete '/admin/logout' => 'admin_sessions#destroy', as: 'admin_logout'

  # Routes for the admin dashboard

  get '/admin/dashboard' => 'admins#dashboard', as: 'admin_dashboard'

  post '/admin/create-user' => 'admins#create_user', as: 'create_user'

  post '/admin/create-test' => 'admins#create_test', as: 'create_test'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TypeTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,900&display=swap" rel="stylesheet">
  </head>
    <header>
      <div class="wrapper">
        <nav class="navigation">
          <a class="logo-link" href="/"><p class="logo">TypeTest</p></a>
          <div class="cta">
            <% if logged_in? %>
              <p class="greeting-text">Hello, <strong><%= current_user.first_name %> </strong> </p>
              <%= link_to 'Logout', logout_path, method: :delete %>
            <% elsif admin_logged_in? %>
              <p class="greeting-text">Welcome, <strong>Admin.</strong> </p>
              <%= link_to 'Logout', admin_logout_path, method: :delete %>
            <% end %>
          </div>
        </nav>
      </div>
    </header>
  <body>
    <%= yield %>
  </body>
</html>